name: Test find_lowest_number.py

on:
  push:
    branches:
      - main

jobs:
  test-find-lowest:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Run test cases
      - name: Run Test Cases
        run: |
          # Test 1
          cp .github/test_data/.github/test1_input.txt .github/test_data/.github/numbers.txt
          python3 find_lowest_number.py .github/test_data/numbers.txt .github/output1.txt
          diff .github/output1.txt .github/test_data/test1_expected.txt
