name: Test find_lowest_number.py

on:
  push:
    branches:
      - main

jobs:
  test-find-lowest:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Run test cases
      - name: Run Test Cases
        run: |
          # Test 1
          - name: List all files in the repository
          run: ls -R
          - name: List files in test_data
            run: ls test_data
         

